apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain # default value is Delete
volumeBindingMode: WaitForFirstConsumer  # disk will be created when pod is getting created
