apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: roboshop
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone : us-east-1c
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"  # headless service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: praneeth2701/mysql:v2
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"   # here we used ebs dynamic
      resources:
        requests:
          storage: 2Gi