apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: roboshop
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone : us-east-1c
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless"  # headless service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: praneeth2701/rabbitmq:v2
        envFrom:
        - secretRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"   # here we used ebs dynamic
      resources:
        requests:
          storage: 2Gi