apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: roboshop
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone : us-east-1c
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"  # headless service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: praneeth2701/mongodb:v2
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"   # here we used ebs dynamic
      resources:
        requests:
          storage: 2Gi